# Generated by Django 4.1.1 on 2023-05-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_project_thumbnaill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnaill',
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
